Walk up to svn root before running svn-git-up logic

diff --git a/svn-git-up b/svn-git-up
--- a/svn-git-up
+++ b/svn-git-up
@@ -3,10 +3,19 @@
 #
 # Pass a branch name like 4.6 as the sole argument to checkout that branch. Otherwise, master/trunk is checked out.
 
+while [[ ! -e .svn ]] && [[ $( pwd ) != '/' ]]; do
+	cd ..
+done
+if [[ ! -e .svn ]]; then
+	echo "Error: Unable to find svn root."
+	exit 1
+fi
+if [[ ! -e .git ]]; then
+	echo "Error: There is no git directory."
+	exit 1
+fi
+
 set -ex
-
-cd "$(dirname $0)"
-
 git fetch origin --tags
 
 git_branch=master
